README.md

we don't know in the repo where to find the website. - added a link

adds webpage url to Readme

---

Makefile
README.md
netlify.toml
scripts/podcast-feed-to-content.py
scripts/requirements.txt

Whenever we publish a new podcast episode, we create a redirect in Netlify like `/episodes/<number>`.
This Pull Request introduces a small automation that will
1. Check which podcast episodes are there
2. Creates the particular netlify redirect configuration
3. Writes the netlify.toml file with the new redirect
It also respects existing redirects.
Here is a sample output of a run where nothing is happening.
```sh
$ make update-redirects 
python ./scripts/podcast-feed-to-content.py redirect
2022-06-06 10:34:12,859 [INFO] Skipping redirect processing for episode 0: Redirect exists already.
2022-06-06 10:34:12,859 [INFO] Skipping redirect processing for episode 1: Redirect exists already.
2022-06-06 10:34:12,859 [INFO] Skipping redirect processing for episode 2: Redirect exists already. …
```

Fix 25: Automate creation of redirects for netlify.toml

---

Makefile
README.md
netlify.toml
scripts/podcast-feed-to-content.py
scripts/requirements.txt

This Pull Request DEPENDS ON https://github.com/EngineeringKiosk/webpage/pull/39
FIRST MERGE https://github.com/EngineeringKiosk/webpage/pull/39 - Then rebase this one.
It adds a few simple basic log lines to the python script command "sync".
Just a bit of visibility.

Add logging to Python script "sync" command

---

scripts/podcast-feed-to-content.py

Automatically pulls the single view link for the episode from Apple Podcasts.
If this is merged, the GitHub Action for syncing needs to be triggered once.

Podcast Episode Sync: Retrieve Apple Podcast Episode Single view

---

src/pages/deutsche-tech-podcasts.astro

- design of list adapted
- section incl. PR button below list
- intro text of list changed

design of podcast list changed and PR button at the end of list added

---

src/pages/blog/post/die-engineering-kiosk-website.mdx

While looking at your Blog post, I noticed a weird sentence structure which was probably caused by changing the wording multiple times while writing the post. 
Since the code is open source, I thought I'd just fix it myself and send you a PR

fix sentence structure

---

src/pages/blog/post/sql-injections.mdxx

> You are attempting to render <PodcastEpisodeBlogpostAd client:load />, but PodcastEpisodeBlogpostAd is an Astro component. Astro components do not render in the client and should not have a hydration directive. Please use a framework component for client rendering.

Remove hydration directive log output

---

src/components/PodcastEpisodeListing.astro

@woolfg Checkout the preview netlify page

Add "Alle Episoden anzeigen" button after podcast listing on index page

---

src/scripts/urlify.js

Related: http://localhost:3000/deutsche-tech-podcasts/net-podcasts/

Fix bug: 404 with .net tag

---

src/data/tags.json
src/pages/podcast/episode/15-source-code-kommentare-git-commits-messages-merge-commits-und-branch-visualisierungs-kunst.md
src/pages/podcast/episode/16-code-reviews-nützlich-oder-bremsen-nur-ein-gutes-team.md
src/pages/podcast/episode/31-ich-automatisiere-mir-die-welt-wie-sie-mir-gefällt-mit-github-actions.md

added seo description to podcast tags

SEO tag descriptions

---

src/pages/kiosk-betreiber/wolfgang-gassler.astro
src/pages/kontakt.astro

@woolfg On two sentences, a new change is required. Please adjust this PR.

Wolfgang: Remove Amsterdam location

---

src/components/Nav.astro

- fix mobile bug of crunshed logo
- icon for german podcasts nav item

Mobile bug and nice icon

---

src/components/Nav.astro

What is the change?
1. Add Community to top line navigation
2. Remove "Home" link
3. Shorten "Deutsche Tech Podcast" links

Navigation: Add Community to top line navigation

---

.github/workflows/links.yml
.lychee.toml

- ignore podcast links
- check other links on website and links in sitemap

Lychee tweaks

---

src/data/german-tech-podcasts-tags.json
src/pages/deutsche-tech-podcasts/index.astro

German Tech Podcasts: Tag listing on page

---

src/components/MeetupEvent.astro
src/components/MeetupListing.astro
src/pages/meetup/alps/archive/index.astro
src/pages/meetup/alps/index.astro
src/pages/meetup/alps/meetups/000-openreply.md
src/pages/meetup/alps/meetups/001-openreply.md
src/pages/meetup/alps/meetups/002-openreply.md
src/scripts/date.js

https://developers.google.com/search/docs/appearance/structured-data/event

Alps structure

---

src/components/PodcastEpisodeTranscript.astro
src/components/PodcastEpisodeTranscriptLine.astro
src/layouts/podcast-episode.astro
src/styles/podcast_episode.scss

- optimize transcript UI, fix Transcript: Add Hover background color and a padding #582
- hardening js, fix Transcript: Clickhandler sometimes throws an error #583

UI & JS optimzation on transcripts

---

src/layouts/podcast-episode.astro
src/styles/podcast_episode.scss

- remove double newlines
- tighten space between timestamps
- remove one feedback section

fix Cleanup shownotes #588

---

src/layouts/podcast-episode.astro
src/scripts/date.js
src/styles/podcast_episode.scss

What is missing:
* Play-Icon next to a chapter if you hover over
@woolfg Can you add this icon and merge it if you are happy?

Fix #584: Make chapters in the shownotes clickable and playable

---

src/components/MainHead.astro
src/layouts/podcast-episode.astro

- remove transitions
- polling for iframe
- small JS optimizations

fix throwing errors with player

---

src/pages/meetup/alps/index.astro

register directly to the new rsv system. works even without js.

use new rsvp system

---

src/components/Nav.astro
src/pages/index.astro

- we have a proper menu on a common resolution of around 1024px now
- added important platform icons on mobile view on top in menu bar
- optimized proportion of text (responsivness)

Optimize UI/responsivness

---

src/pages/meetup/alps/index.astro
src/pages/meetup/alps/meetups/2306-openreply.md
src/pages/meetup/alps/meetups/2307-openreply.md
src/pages/meetup/alps/meetups/2309-openreply.md
src/pages/meetup/alps/meetups/2310-txture.md
src/pages/meetup/alps/meetups/2311-swarmanalytics.md
src/pages/meetup/alps/meetups/2312-dynatrace.mdx
src/pages/meetup/alps/meetups/2401-florianmatthias.mdx

Dependend on https://github.com/EngineeringKiosk/rsvp/pull/1

Use eventId from event configs

---

src/components/PodcastEpisodeListing.astro
src/components/PodcastEpisodePreview.astro
src/pages/linktree.astro

Fix #626
Additionally, we drop the description on the linktree site.

Linktree: Show the latest + hand-picked episodes

---

src/components/Footer.astro
src/data/podcast-info.json
src/pages/kontakt.astro
src/pages/linktree.astro

Fix https://github.com/EngineeringKiosk/webpage/issues/625
The suggestion to build pre-defined components (li) that are stylable from outside is nice, but from my side not needed at the moment.
We do it, once we have a proper benefit.
This one here is also only cosmetic.
FYI @woolfg

Move Social Links into a data.json file and re-use them

---

src/content/podcast/102-quereinstieg-in-die-software-entwicklung-mit-melanie-patrick.md
src/content/podcast/104-präsentieren-mit-wirkung-public-speaking-und-storytelling-mit-anna-momber.md
src/content/podcast/50-dei-erhöht-innovation-und-den-finanziellen-erfolg.md
src/content/podcast/77-kinder-coding-und-ai-die-zukunft-der-informatik-bildung-mit-diana-knodel.md
src/content/podcast/85-von-entwicklerin-zur-engineering-managerin-erfahrungen-und-learnings-mit-isabelle-glasmacher.md
src/content/podcast/93-barbara-liskov-das-l-in-solid-liskovsches-substitutionsprinzip-abstraktion.md
src/data/tags.json

can be also used to identify interviews with female guests by combining interview and womenintech tag

introduction of tag women in tech

---

netlify.toml

link for roll-up QR Code for meetup alps

add roll-up redirect

---

src/content/podcast/139-security-engineering-und-hacking-wettbewerbe-mit-frederik-braun-von-mozilla.md
src/content/podcast/141-datenjournalismus-zwischen-grafik-und-fakten-mit-michael-kreil.md
src/content/podcast/146-warum-ist-doom-so-faszinierend-für-die-software-entwicklung.md
src/content/podcast/147-mechanische-tastaturen-vom-klick-zum-kult-mit-philipp-hoeler-lutz-von-click-clack-hack.md
src/content/podcast/46-welches-problem-löst-docker.md
src/content/podcast/48-der-layer-unter-docker-containerd-kubernetes-container-runtime-interface-cri-o-und-open-container-initiative-oci.md
src/content/podcast/52-asynchrone-verarbeitung-durch-message-queues-vor-und-nachteile.md
src/content/podcast/54-key-value-store-redis-einsatzmöglichkeiten-fallstricke-datenstrukturen-hyperloglog-und-flüchtige-persistenz.md
src/content/podcast/58-software-updates-alte-software-long-term-support-und-end-of-life-dates.md
src/content/podcast/79-font-engineering-und-schriftarten-fürs-programmieren-mit-philipp-acsany.md

This pull request removes episodes that only touch on open source topics and are not the main focus.

Focus on open source topics

---

scripts/podcast_feed_to_content.py
src/content/config.ts
src/layouts/podcast-episode.astro

We host on RTL+ but we never filled this attribute. Lets remove it, if we are not using it

Remove `rtlplus` from frontmatter attribute

---

src/data/episodes-best-of.json

Automated update of **podcast episodes best-of**.

chore: update podcast episodes best-of
